### ISSUE TITLE
Project home page 404 Not Found

### ISSUE THREAD

**Issue by CaptSolo** [jrvosse/amalgame#12]
The project link http://semanticweb.cs.vu.nl/amalgame/ (at the top of Amalgame's GitHub page) returns 404 Not Found.

**Comment by jrvosse** [comment]
Oops, I missed this one.  Looks like a hangover from a server crash.  I'm looking into this.

Thanks for reporting this,

Jacco

**Comment by jrvosse** [comment]
We're back!

Thanks again, Jacco
