### ISSUE TITLE
Search on SDMX side of Amalgame doesn't work

### ISSUE THREAD

**Issue by mfaden** [jrvosse/amalgame#7]
At http://87.106.253.23/amalgame/amalgame/app/build?strategy=http://localhost/ns/strategy4 I started a manual correspondence evaluation. On the STW side the search works (screenshot 1), but it doesn't on SDMX side (screenshot 2).

![amalgamesuche](https://cloud.githubusercontent.com/assets/8351173/4951761/74fe1be6-666b-11e4-9e09-126b40c16f5c.jpg)

**Comment by jrvosse** [comment]
I just assume this has been fixed, if not please reopen.

**Comment by mfaden** [comment]
Hi Jacco!
Sorry for replying so late. Joachim and I have been in vacation, but now we start anew.
Since start with an all new version of Amalgame, we state this issue closed and see if we have new/old problems/questions. I neccessary we'll reopen. ;>)
Thanks a lot!
Sincerely
Manfred
